### PR TITLE
Update ImportsService.php

### PR DESCRIPTION
**Pull request by phoob**
Solve `yii\base\ErrorException: Trying to get property of non-object in /var/www/html/vendor/putyourlightson/craft-campaign/src/services/ImportsService.php:225`

### CODE REVIEW

**Comment by putyourlightson** [comment]
Thanks for the pull request. In what situation are you encountering this exception? I can’t replicate it locally.

**Comment by phoob** [comment]
Hmm.. I encounter it when trying to import a csv file..

**Comment by putyourlightson** [comment]
Hmm, from a CSV file? I just don't quite get why `Craft::$app->getUser()->getIdentity()` would return `null` given that you are importing while logged into the control panel.

**Comment by putyourlightson** [comment]
Any idea on why this might have happened in your environment and not mine? I'd like to get to the bottom of it so I can issue a permanent fix.

**Comment by putyourlightson** [comment]
Fixed, thank you.

**Pull request closed without merging**
