### PR TITLE
German translation

### PR DESCRIPTION
**Pull request by andreasbecker**
Translated all the phrases into German except for the plugin name which stays "Campaign"

### CODE REVIEW

**Comment by bencroker** [comment]
Thank you Andreas!! Will take a closer look and then merge this in.

**Comment by bencroker** [comment]
I changed "Abbestellen" to "Abmelden" for consistency, in https://github.com/putyourlightson/craft-campaign/commit/e7dbb413a3ed3578edc6c03d2096ec236e7ce1fd. 

Do you think it would make sense to translate "complained" and "bounced"?
Screenshot 2022-02-26 at 12 43 53

**Comment by andreasbecker** [comment]
No, as far as I know there is no appropriate translation for "bounced" and "complained" in this context. You could say "rückgesendet" and "moniert" respectively, but it sounds a little weird and I've never heard that concerning the email status.

I also haven't translated "blocked". But that could actually be translated as "blockiert". You could change this.

**Comment by bencroker** [comment]
Makes sense, thanks! I made some additional tweaks so that the data tables will be translated too.

Screenshot 2022-02-26 at 19 50 46

**Pull request merged**
