### PR TITLE
Add French translation

### PR DESCRIPTION
**Pull request by scandella**
First commit.

As we discussed before, this is my own version of what I consider to be a usable french translation.
So I've changed the main wording concepts of the plugin to be understandable for a non technical french user.

The main differences are:
'Campaign' become 'Newsletter'
'Sendout' become 'Campagne'

In english you have this concept, "Sendout" that does not translate well in French. A 'Campagne d’envoi' is more suitable, but it conflict with your 'Campaign" concept and branding.
To resolve this problem, I've assumed that a user wants to create some 'Newsletter' and send then by creating some 'Campagnes'.
I get that, in English, 'Campaign' is best to label the main action that the plugin is made for: creating some content to be send to multiple recipients. Because the content can be a transactionnal email or a 'welcome email' or any type of content and not just a 'newsletter", 'campaign' is a more suitable generic concept.
But due to the taste for the english words in France, everybody refer to any marketing mail content by 'newsletter', whatever its nature is.

Although, as I totally invert your wording, I would understand if you refused this contribution, but I think it is the best move for a french version.

Best,

### CODE REVIEW

**Comment by bencroker** [comment]
Thank you for the PR and for the explanation!! I understand how technical terms don't always translate well, therefore I am in agreement with your renaming "campaigns" to "newsletters". I have invite a few other French speakers to take a look and am waiting for a few other language translations to be submitted, before I merge this.

**Comment by ockam** [comment]
I would suggest `infolettre` instead of `newsletter`, but that may be more an `fr-ca` translation.

**Comment by scandella** [comment]
> I would suggest `infolettre` instead of `newsletter`, but that may be more an `fr-ca` translation.

Yes, indeed, that must be a Canadian usage, because we never use this word in France.
The official recommendation for a pure french word is "Lettre d'information", but nobody use it neither!

**Comment by bencroker** [comment]
Merged, thanks @scandella!

**Comment by bencroker** [comment]
@scandella there are a few missing translations that I just added for the pending release. Could you please fill them in if you have time? 

The quickest way to find them is to search for `=> ''` in https://github.com/putyourlightson/craft-campaign/blob/develop/src/translations/fr/campaign.php

**Comment by bencroker** [comment]
Released in version 1.22.0, thanks again @scandella.

**Pull request merged**
